using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Laserbeam.BusinessObject.Common.Constants
{
   public class BusSettingConstants
    {
        public const string Merit = "Merit";
        public const string Adjustment = "Adjustment";
        public const string Lumpsum = "Lumpsum";
        public const string Prorate = "Prorate";
        public const string ApplyMeritDiscretion = "ApplyMeritDiscretion";
        public const string ApplyBudgetCalculations = "ApplyBudgetCalculations";
        public const string ApplyAdjustmentCalculations = "ApplyAdjustmentCalculations";
        public const string ProrateIncreaseStartDate = "ProrateIncreaseStartDate";
        public const string ProrateIncreaseEndDate = "ProrateIncreaseEndDate";
        public const string ProrationType = "ProrationType";
        public const string ProrationLength = "ProrationLength";
        public const string ProrationLengthtoInclude = "ProrationLengthtoInclude";
        public const string LumpsumType = "LumpsumType";
        public const string RangeMaxPct = "RangeMaxPct";
        public const string MeritOverrideHardStop = "MeritOverrideHardStop";
        public const string MeritOverrideSoftStop = "MeritOverrideSoftStop";
        public const string MeritIncreaseWithinGuideline = "MeritIncreaseWithinGuideline";
        public const string MandatoryJustification = "MandatoryJustification";
        public const string RoundingMeritPct = "RoundingMeritPct";
        public const string RoundingMeritHourly = "RoundingMeritHourly";
        public const string RoundingMeritAnnual = "RoundingMeritAnnual";
        public const string DecimalMeritPct = "DecimalMeritPct";
        public const string DecimalMeritHourly = "DecimalMeritHourly";
        public const string DecimalMeritAnnual = "DecimalMeritAnnual";
        public const string RoundingLumpSumPct = "RoundingLumpSumPct";
        public const string RoundingLumpSumHourly = "RoundingLumpSumHourly";
        public const string RoundingLumpSumAnnual = "RoundingLumpSumAnnual";
        public const string DecimalLumpSumPct = "DecimalLumpSumPct";
        public const string DecimalLumpSumHourly = "DecimalLumpSumHourly";
        public const string DecimalLumpSumAnnual = "DecimalLumpSumAnnual";
        public const string RoundingAdjustmentPct = "RoundingAdjustmentPct";
        public const string RoundingAdjustmentHourly = "RoundingAdjustmentHourly";
        public const string RoundingAdjustmentAnnual = "RoundingAdjustmentAnnual";
        public const string DecimalAdjustmentPct = "DecimalAdjustmentPct";
        public const string DecimalAdjustmentHourly = "DecimalAdjustmentHourly";
        public const string DecimalAdjustmentAnnual = "DecimalAdjustmentAnnual";
        public const string RoundingCompaRatioPct = "RoundingCompaRatioPct";
        public const string RoundingCompaRatioHourly = "RoundingCompaRatioHourly";
        public const string RoundingCompaRatioAnnual = "RoundingCompaRatioAnnual";
        public const string DecimalCompaRatioPct = "DecimalCompaRatioPct";
        public const string DecimalCompaRatioHourly = "DecimalCompaRatioHourly";
        public const string DecimalCompaRatioAnnual = "DecimalCompaRatioAnnual";
        public const string RoundingBonusPct = "RoundingBonusPct";
        public const string RoundingBonusHourly = "RoundingBonusHourly";
        public const string RoundingBonusAnnual = "RoundingBonusAnnual";
        public const string DecimalBonusPct = "DecimalBonusPct";
        public const string DecimalBonusHourly = "DecimalBonusHourly";
        public const string DecimalBonusAnnual = "DecimalBonusAnnual";
        public const string RatingDisplay = "RatingDisplay";
        public const string MeritOverrideNoJustification = "MeritOverrideNoJustification";
        public const string TCC = "TCC";
        public const string RatingDropdown = "RatingDropdown";
        public const string BudgetPercent = "BudgetPercent";
        public const string EmployeeNameFormat = "EmployeeNameFormat";
        public const string UserNameFormat = "UserNameFormat";
        public const string MultiCurrency = "MultiCurrency";
        public const string SortOrderEmployeeNameFormat = "SortOrderEmployeeNameFormat";
        public const string Promotion = "Promotion";
        public const string CurrencyCode = "CurrencyCode";
        public const string RoundingPromotionPct = "RoundingPromotionPct";
        public const string RoundingPromotionHourly = "RoundingPromotionHourly";
        public const string RoundingPromotionAnnual = "RoundingPromotionAnnual";
        public const string DecimalPromotionPct = "DecimalPromotionPct";
        public const string DecimalPromotionHourly = "DecimalPromotionHourly";
        public const string DecimalPromotionAnnual = "DecimalPromotionAnnual";
        public const string LTIP = "LTIP";
        public const string DateFormat = "DateFormat";
        public const string CurrencyFormat = "CurrencyFormat";
        public const string MeritCalculation = "MeritCalculation";
        public const string RoundNewSalaryPct = "RoundNewSalaryPct";
        public const string RoundNewSalaryHourly = "RoundNewSalaryHourly";
        public const string RoundNewSalaryAnnual = "RoundNewSalaryAnnual";
        public const string DecimalNewSalaryPct = "DecimalNewSalaryPct";
        public const string DecimalNewSalaryHourly = "DecimalNewSalaryHourly";
        public const string DecimalNewSalaryAnnual = "DecimalNewSalaryAnnual";
        public const string RangeMaxAmt = "RangeMaxAmt";
        public const string EmployeeNameEmailFormat = "EmployeeNameEmailFormat";
        public const string WorkFlow = "WorkFlow";
        public const string EitherMeritOrLumpSum = "EitherMeritOrLumpSum";
        public const string ApplyBudgetMethod = "ApplyBudgetMethod";
        public const string RoundingBudgetPerc = "RoundingBudgetPerc";
        public const string RoundingBudgetDol = "RoundingBudgetDol";
        public const string DecimalBudgetPerc = "DecimalBudgetPerc";
        public const string DecimalBudgetDol = "DecimalBudgetDol";
        public const string BudgetProrate = "BudgetProrate";
        public const string BudgetProrateIncreaseStartDate = "BudgetProrateIncreaseStartDate";
        public const string BudgetProrateIncreaseEndDate = "BudgetProrateIncreaseEndDate";
        public const string BudgetProrationType = "BudgetProrationType";
        public const string BudgetProrationDuration = "BudgetProrationDuration";
        public const string BudgetProrationDatesPerMonth = "BudgetProrationDatesPerMonth";
        public const string MeritValuesReCalculate = "MeritValuesReCalculate";
        public const string AutoCalculateLumpSum = "AutoCalculateLumpSum";
        public const string LumpSumRuleTurnOff = "LumpSumRuleTurnOff";
        public const string WorkFlowMode = "WorkFlowMode";
        public const string WorkFlowLevel = "WorkFlowLevel";
        public const string SupportHours = "SupportHours";
        public const string IsSampleData = "IsSampleData";
        public const string MarketPayRange = "MarketPayRange";
        public const string Bonus = "Bonus";
        public const string IndividualPortion = "IndividualPortion";
        public const string GlobalPortion = "GlobalPortion";
        public const string ComparativeRatio = "ComparativeRatio";
        public const string RoundCurrentSalaryPct = "RoundCurrentSalaryPct";
        public const string RoundCurrentSalaryHourly = "RoundCurrentSalaryHourly";
        public const string RoundCurrentSalaryAnnual = "RoundCurrentSalaryAnnual";
        public const string DecimalCurrentSalaryPct = "DecimalCurrentSalaryPct";
        public const string DecimalCurrentSalaryHourly = "DecimalCurrentSalaryHourly";
        public const string DecimalCurrentSalaryAnnual = "DecimalCurrentSalaryAnnual";
        public const string EnableSSO = "EnableSSO";
        public const string IDPEndPoint = "IDPEndPoint";

    }
}
