//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.TenantMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public int UserNum { get; set; }
        public string EmailAddress { get; set; }
        public string UserName { get; set; }
        public string UserFirstName { get; set; }
        public string UserLastName { get; set; }
        public string UserPassword { get; set; }
        public string SecretKey { get; set; }
        public byte FailedLoginAttempts { get; set; }
        public string AppUserRole { get; set; }
        public byte AppUserStatusNum { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastLogoutDate { get; set; }
        public string TenantName { get; set; }
        public string CompanyName { get; set; }
        public string Country { get; set; }
        public string PinCode { get; set; }
        public string PhoneNumber { get; set; }
        public string ExtensionNumber { get; set; }
        public Nullable<bool> IsTenantCreated { get; set; }
    
        public virtual AppUserStatu AppUserStatu { get; set; }
    }
}
