//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.TenantMaster
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantConnection
    {
        public int TenantNum { get; set; }
        public short ProductNum { get; set; }
        public string DatabaseServer { get; set; }
        public string DatabaseName { get; set; }
        public string DatabaseUserId { get; set; }
        public string DatabasePassword { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Tenant Tenant { get; set; }
    }
}
