//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.Resource.HR.LoginResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laserbeam.Resource.HR.LoginResources.LoginResource", typeof(LoginResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string HeaderChangePassword {
            get {
                return ResourceManager.GetString("HeaderChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot your Password?.
        /// </summary>
        public static string HeaderForgotPassword {
            get {
                return ResourceManager.GetString("HeaderForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string LabelConfirmPassword {
            get {
                return ResourceManager.GetString("LabelConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string LabelNewPassword {
            get {
                return ResourceManager.GetString("LabelNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LabelUserID {
            get {
                return ResourceManager.GetString("LabelUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password?.
        /// </summary>
        public static string LinkChangePassword {
            get {
                return ResourceManager.GetString("LinkChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string LinkForgotPassword {
            get {
                return ResourceManager.GetString("LinkForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with my company credentials.
        /// </summary>
        public static string LinkSSOLogIn {
            get {
                return ResourceManager.GetString("LinkSSOLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have tired 5 failed login attempts. Please try again after 30 minutes, if you don’t remember the password please click on the “Forgot Password?.
        /// </summary>
        public static string MessageAccountLocked {
            get {
                return ResourceManager.GetString("MessageAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is locked.Please contact the administrator.
        /// </summary>
        public static string MessageContactAdmin {
            get {
                return ResourceManager.GetString("MessageContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your default password has expired.
        /// </summary>
        public static string MessageDefaultPasswordExpired {
            get {
                return ResourceManager.GetString("MessageDefaultPasswordExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password and new password should be different.
        /// </summary>
        public static string MessageDifferentPasswords {
            get {
                return ResourceManager.GetString("MessageDifferentPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sending failed!.
        /// </summary>
        public static string MessageForgotPasswordFailure {
            get {
                return ResourceManager.GetString("MessageForgotPasswordFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default password has been sent to your email address.
        /// </summary>
        public static string MessageForgotPasswordSuccess {
            get {
                return ResourceManager.GetString("MessageForgotPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is disabled.Please contact the administrator.
        /// </summary>
        public static string MessageInactive {
            get {
                return ResourceManager.GetString("MessageInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! It looks like the email address/password combination you have entered is invalid. Please try again or click ‘Forgot Password’?.
        /// </summary>
        public static string MessageInvalidPassword {
            get {
                return ResourceManager.GetString("MessageInvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user.
        /// </summary>
        public static string MessageInvalidUser {
            get {
                return ResourceManager.GetString("MessageInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be alphanumeric with atleast eight characters!.
        /// </summary>
        public static string MessageModeratePassword {
            get {
                return ResourceManager.GetString("MessageModeratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been changed.
        /// </summary>
        public static string MessagePasswordChanged {
            get {
                return ResourceManager.GetString("MessagePasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password and Confirm Password should match.
        /// </summary>
        public static string MessagePasswordMismatch {
            get {
                return ResourceManager.GetString("MessagePasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter 1 Alphabet.
        /// </summary>
        public static string MessagePasswordNotStrongEnough {
            get {
                return ResourceManager.GetString("MessagePasswordNotStrongEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not meet the above standard.
        /// </summary>
        public static string MessagePasswordStandard {
            get {
                return ResourceManager.GetString("MessagePasswordStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be atleast 12 characters with one uppercase, one lowercase, one numeric and one special character!.
        /// </summary>
        public static string MessageStrongPassword {
            get {
                return ResourceManager.GetString("MessageStrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contains atleast four characters!.
        /// </summary>
        public static string MessageWeakPassword {
            get {
                return ResourceManager.GetString("MessageWeakPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a new confirm password.
        /// </summary>
        public static string RequiredConfirmPassword {
            get {
                return ResourceManager.GetString("RequiredConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a new password.
        /// </summary>
        public static string RequiredNewPassword {
            get {
                return ResourceManager.GetString("RequiredNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email address.
        /// </summary>
        public static string RequiredUserID {
            get {
                return ResourceManager.GetString("RequiredUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Error. Your compass account is not active. Please contact your administrator for more information..
        /// </summary>
        public static string SSOInactiveUser {
            get {
                return ResourceManager.GetString("SSOInactiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Error. Your compass account information could not be identified. Please contact your administrator for more information..
        /// </summary>
        public static string SSOInvalidUser {
            get {
                return ResourceManager.GetString("SSOInvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your log in attempt using single sign-on has failed. Please contact your administrator for more information..
        /// </summary>
        public static string SSOValidationMessage {
            get {
                return ResourceManager.GetString("SSOValidationMessage", resourceCulture);
            }
        }
    }
}
