//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEmail
    {
        public int AppEmailID { get; set; }
        public string EmailSubject { get; set; }
        public string EmailBody { get; set; }
        public string EmailScript { get; set; }
        public string EmailDescr { get; set; }
        public bool Active { get; set; }
        public Nullable<byte> EmailOrderby { get; set; }
        public string EmailKey { get; set; }
        public Nullable<bool> UserTemplate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
