//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMessage
    {
        public AppMessage()
        {
            this.UserMessages = new HashSet<UserMessage>();
        }
    
        public int AppMessageID { get; set; }
        public string MessageSubject { get; set; }
        public string MessageBody { get; set; }
        public string MessageScript { get; set; }
        public string MessageDescr { get; set; }
        public bool MessageType { get; set; }
        public bool Active { get; set; }
        public Nullable<byte> MessageOrderby { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<UserMessage> UserMessages { get; set; }
    }
}
