//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppMenu
    {
        public int AppMenuID { get; set; }
        public string MenuName { get; set; }
        public Nullable<int> MenuParentNum { get; set; }
        public string MenuLinks { get; set; }
        public Nullable<int> MenuOrderBy { get; set; }
        public string menuid { get; set; }
        public bool AdminLinks { get; set; }
        public bool Active { get; set; }
    }
}
