//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public AppUser()
        {
            this.DailyTasks = new HashSet<DailyTask>();
            this.EmployeeApprovalDetails = new HashSet<EmployeeApprovalDetail>();
            this.EmployeeCompComments = new HashSet<EmployeeCompComment>();
            this.EmployeeCompComments1 = new HashSet<EmployeeCompComment>();
            this.EmployeeCompCommentStatus = new HashSet<EmployeeCompCommentStatu>();
            this.EmployeeWorkflowCommentStatus = new HashSet<EmployeeWorkflowCommentStatu>();
            this.FeedBacks = new HashSet<FeedBack>();
            this.Budgets = new HashSet<Budget>();
            this.ProxyGroups = new HashSet<ProxyGroup>();
            this.ProxyManagers = new HashSet<ProxyManager>();
            this.ProxyScripts = new HashSet<ProxyScript>();
            this.UserMenus = new HashSet<UserMenu>();
            this.UserMessages = new HashSet<UserMessage>();
            this.SupportTaskComments = new HashSet<SupportTaskComment>();
        }
    
        public int UserNum { get; set; }
        public Nullable<int> EmployeeNum { get; set; }
        public string UserID { get; set; }
        public string EmployeeID { get; set; }
        public string LoginID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public string UserPassword { get; set; }
        public string DefaultPassword { get; set; }
        public string EmailID { get; set; }
        public string ProxyID { get; set; }
        public string UserGroup { get; set; }
        public int UserRoleNum { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LastLoginDt { get; set; }
        public Nullable<System.DateTime> LastLogOutDt { get; set; }
        public Nullable<int> AppUserStatusID { get; set; }
        public Nullable<int> XMLProcessID { get; set; }
        public Nullable<System.DateTime> SSOLastLoginDate { get; set; }
        public Nullable<System.DateTime> SSOLastLogOutDate { get; set; }
        public string ApplicationSessionID { get; set; }
        public Nullable<bool> DefaultPasswordExpired { get; set; }
        public string SecretKey { get; set; }
        public bool MarkAsDelete { get; set; }
        public Nullable<System.DateTime> LockedDate { get; set; }
        public Nullable<bool> MailDeliveryStatus { get; set; }
        public Nullable<System.DateTime> MailDeliveryDate { get; set; }
        public Nullable<bool> IsWizardExpired { get; set; }
        public Nullable<int> WizardStepsCompleted { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDefaultUser { get; set; }
        public Nullable<int> ChatStatus { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public Nullable<bool> IsAdminAccess { get; set; }
        public Nullable<int> AdminUserNum { get; set; }
        public Nullable<int> AdminEmpNum { get; set; }
    
        public virtual AppUserRole AppUserRole { get; set; }
        public virtual AppUserStatu AppUserStatu { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<DailyTask> DailyTasks { get; set; }
        public virtual ICollection<EmployeeApprovalDetail> EmployeeApprovalDetails { get; set; }
        public virtual ICollection<EmployeeCompComment> EmployeeCompComments { get; set; }
        public virtual ICollection<EmployeeCompComment> EmployeeCompComments1 { get; set; }
        public virtual ICollection<EmployeeCompCommentStatu> EmployeeCompCommentStatus { get; set; }
        public virtual ICollection<EmployeeWorkflowCommentStatu> EmployeeWorkflowCommentStatus { get; set; }
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public virtual ICollection<Budget> Budgets { get; set; }
        public virtual ICollection<ProxyGroup> ProxyGroups { get; set; }
        public virtual ICollection<ProxyManager> ProxyManagers { get; set; }
        public virtual ICollection<ProxyScript> ProxyScripts { get; set; }
        public virtual ICollection<UserMenu> UserMenus { get; set; }
        public virtual ICollection<UserMessage> UserMessages { get; set; }
        public virtual ICollection<SupportTaskComment> SupportTaskComments { get; set; }
    }
}
