//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budget
    {
        public int BudgetNum { get; set; }
        public int EmpJobNum { get; set; }
        public int CompensationTypeNum { get; set; }
        public decimal Budget1 { get; set; }
        public decimal Spent { get; set; }
        public Nullable<decimal> LTIPBudget { get; set; }
        public Nullable<decimal> LTIPSpent { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public decimal PromotionSpent { get; set; }
        public decimal AdjustmentSpent { get; set; }
        public Nullable<decimal> LumpSumSpent { get; set; }
        public Nullable<decimal> BonusBudget { get; set; }
        public Nullable<decimal> BonusSpent { get; set; }
        public Nullable<decimal> BudgetPct { get; set; }
        public Nullable<decimal> ProratedBudget { get; set; }
        public Nullable<decimal> ProratedBudgetPct { get; set; }
        public Nullable<decimal> BudgetProration { get; set; }
        public Nullable<decimal> AdjustedBudget { get; set; }
        public Nullable<decimal> AdjustedBudgetPct { get; set; }
    
        public virtual CompensationType CompensationType { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual EmployeeJob EmployeeJob { get; set; }
    }
}
