//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusSetting
    {
        public int BusSettingID { get; set; }
        public string KeyId { get; set; }
        public string KeyValue { get; set; }
        public string KeyDataValue { get; set; }
        public string Descr { get; set; }
        public Nullable<bool> IsChanged { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
