//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CategoryNum { get; set; }
        public string CategoryCode { get; set; }
        public string CategoryDescr { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
