//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompensationType
    {
        public CompensationType()
        {
            this.Budgets = new HashSet<Budget>();
        }
    
        public int CompensationTypeNum { get; set; }
        public string CompensationTypeShortName { get; set; }
        public string CompensationTypeDescr { get; set; }
        public string CompensationTransactionReference { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<Budget> Budgets { get; set; }
    }
}
