//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public Currency()
        {
            this.ExchangeRates = new HashSet<ExchangeRate>();
            this.ExchangeRates1 = new HashSet<ExchangeRate>();
            this.EmployeeJobs = new HashSet<EmployeeJob>();
        }
    
        public int CurrencyCodeNum { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencyCodeDescr { get; set; }
        public string CultureCode { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ExchangeRate> ExchangeRates { get; set; }
        public virtual ICollection<ExchangeRate> ExchangeRates1 { get; set; }
        public virtual ICollection<EmployeeJob> EmployeeJobs { get; set; }
    }
}
