//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyTask
    {
        public int TaskNum { get; set; }
        public int UserNum { get; set; }
        public string TaskTitle { get; set; }
        public string TaskDescr { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool TaskCompleted { get; set; }
        public Nullable<System.DateTime> TaskCompletedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
