//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateFormat
    {
        public int DateFormatNum { get; set; }
        public string FormatType { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
