//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class DecimalType
    {
        public int DecimalTypeId { get; set; }
        public string DecimalTypeKey { get; set; }
        public string DecimalTypeValue { get; set; }
        public string Type { get; set; }
        public bool Active { get; set; }
    }
}
