//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTracker
    {
        public string ClientUserID { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public int AppEmailID { get; set; }
        public bool Success { get; set; }
        public string ErrorDescription { get; set; }
        public int EmailTrackerID { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
