//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompNew
    {
        public int EmployeeCompNewNum { get; set; }
        public int EmpJobNum { get; set; }
        public Nullable<decimal> NewSalary { get; set; }
        public Nullable<System.DateTime> SalaryEffectiveDate { get; set; }
        public Nullable<decimal> HrlyNewSalary { get; set; }
        public Nullable<decimal> NewCompaRatio { get; set; }
        public string NewQuartile { get; set; }
        public Nullable<decimal> TotalNewComp { get; set; }
        public string SalaryReasonCode { get; set; }
        public bool CompCompleted { get; set; }
        public bool ExceedCommentProvided { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmployeeJob EmployeeJob { get; set; }
    }
}
