//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompMarket
    {
        public int EmployeeCompMarketNum { get; set; }
        public int EmpJobNum { get; set; }
        public Nullable<decimal> MktQ1 { get; set; }
        public Nullable<decimal> MktQ2 { get; set; }
        public Nullable<decimal> MktQ3 { get; set; }
        public Nullable<decimal> MktQ4 { get; set; }
        public Nullable<decimal> MktQ5 { get; set; }
        public Nullable<decimal> MktMin { get; set; }
        public Nullable<decimal> MktMid { get; set; }
        public Nullable<decimal> MktMax { get; set; }
        public Nullable<decimal> HrlyMktQ1 { get; set; }
        public Nullable<decimal> HrlyMktQ2 { get; set; }
        public Nullable<decimal> HrlyMktQ3 { get; set; }
        public Nullable<decimal> HrlyMktQ4 { get; set; }
        public Nullable<decimal> HrlyMktQ5 { get; set; }
        public Nullable<decimal> HrlyMktMin { get; set; }
        public Nullable<decimal> HrlyMktMid { get; set; }
        public Nullable<decimal> HrlyMktMax { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> NewMktMin { get; set; }
        public Nullable<decimal> NewMktMid { get; set; }
        public Nullable<decimal> NewMktMax { get; set; }
        public Nullable<decimal> HrlyNewMktMin { get; set; }
        public Nullable<decimal> HrlyNewMktMid { get; set; }
        public Nullable<decimal> HrlyNewMktMax { get; set; }
    
        public virtual EmployeeJob EmployeeJob { get; set; }
    }
}
