//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeApprovalDetail
    {
        public EmployeeApprovalDetail()
        {
            this.EmployeeWorkflowCommentStatus = new HashSet<EmployeeWorkflowCommentStatu>();
        }
    
        public int EmployeeApprovalDetailNum { get; set; }
        public int EmpJobNum { get; set; }
        public Nullable<int> ApprovedManager { get; set; }
        public Nullable<int> ApprovedLevel { get; set; }
        public Nullable<byte> ApprovalStatus { get; set; }
        public string Comments { get; set; }
        public Nullable<int> ModuleNum { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual ICollection<EmployeeWorkflowCommentStatu> EmployeeWorkflowCommentStatus { get; set; }
    }
}
