//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompCommentStatu
    {
        public int EmployeeCompCommentStatusId { get; set; }
        public int CommentNum { get; set; }
        public int UserNum { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual EmployeeCompComment EmployeeCompComment { get; set; }
    }
}
