//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMoreInfo
    {
        public int EmployeeMoreInfoNum { get; set; }
        public int EmpJobNum { get; set; }
        public string MoreInfo1 { get; set; }
        public string MoreInfo2 { get; set; }
        public string MoreInfo3 { get; set; }
        public string MoreInfo4 { get; set; }
        public string MoreInfo5 { get; set; }
        public string MoreInfo6 { get; set; }
        public string MoreInfo7 { get; set; }
        public string MoreInfo8 { get; set; }
        public string MoreInfo9 { get; set; }
        public string MoreInfo10 { get; set; }
        public string MoreInfo11 { get; set; }
        public string MoreInfo12 { get; set; }
        public string MoreInfo13 { get; set; }
        public string MoreInfo14 { get; set; }
        public string MoreInfo15 { get; set; }
        public string MoreInfo16 { get; set; }
        public string MoreInfo17 { get; set; }
        public string MoreInfo18 { get; set; }
        public string MoreInfo19 { get; set; }
        public string MoreInfo20 { get; set; }
        public string MoreInfo21 { get; set; }
        public string MoreInfo22 { get; set; }
        public string MoreInfo23 { get; set; }
    }
}
