//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompBonu
    {
        public int EmployeeCompBonusNum { get; set; }
        public int EmpJobNum { get; set; }
        public Nullable<decimal> BonusPct { get; set; }
        public Nullable<decimal> BonusAmt { get; set; }
        public Nullable<bool> BonusEligibility { get; set; }
        public Nullable<decimal> BonusTargetPct { get; set; }
        public Nullable<decimal> BonusTargetAmt { get; set; }
        public Nullable<decimal> AdjustedBonusAmt { get; set; }
        public Nullable<System.DateTime> BonusEffectiveDate { get; set; }
        public Nullable<decimal> BonusTeamAmt { get; set; }
        public Nullable<decimal> BonusIOAmt { get; set; }
        public Nullable<decimal> Payout { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmployeeJob EmployeeJob { get; set; }
    }
}
