//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompComment
    {
        public EmployeeCompComment()
        {
            this.EmployeeCompCommentStatus = new HashSet<EmployeeCompCommentStatu>();
        }
    
        public int EmployeeCompCommentsNum { get; set; }
        public int EmpJobNum { get; set; }
        public int CompensationTypeNum { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
        public virtual EmployeeJob EmployeeJob { get; set; }
        public virtual ICollection<EmployeeCompCommentStatu> EmployeeCompCommentStatus { get; set; }
    }
}
