//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompMerit
    {
        public int EmployeeCompMeritNum { get; set; }
        public int EmpJobNum { get; set; }
        public Nullable<decimal> CompaRatio { get; set; }
        public Nullable<decimal> PositionInQuartile { get; set; }
        public string EmployeeQuartile { get; set; }
        public Nullable<decimal> CurrentAnnualSalary { get; set; }
        public Nullable<decimal> HrlySalary { get; set; }
        public Nullable<decimal> ActualWorkHrs { get; set; }
        public string MeritRange { get; set; }
        public Nullable<decimal> TargetMeritPct { get; set; }
        public Nullable<decimal> TargetMeritAmt { get; set; }
        public Nullable<decimal> MeritPCT { get; set; }
        public Nullable<decimal> MeritAmt { get; set; }
        public Nullable<decimal> HrlyMeritAmt { get; set; }
        public Nullable<decimal> LumpSumAmt { get; set; }
        public Nullable<decimal> LumpSumPCT { get; set; }
        public Nullable<decimal> HrlyLumpSumAmt { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<decimal> MeritPH { get; set; }
        public bool Eligibility { get; set; }
        public string MeritRangeExceed { get; set; }
        public Nullable<decimal> ProRatedPCT { get; set; }
        public Nullable<decimal> ProRation { get; set; }
        public Nullable<decimal> ProRatedAmt { get; set; }
        public string IncrType { get; set; }
        public Nullable<System.DateTime> LastIncrDate { get; set; }
        public Nullable<decimal> TotalWorkHrs { get; set; }
        public Nullable<decimal> CurrentAnnualizedSalary { get; set; }
        public Nullable<decimal> MandatoryIncrease { get; set; }
        public string LastPayChangeReason { get; set; }
        public Nullable<System.DateTime> MeritProrationDate { get; set; }
        public Nullable<System.DateTime> LumpSumEffectiveDate { get; set; }
        public Nullable<decimal> FTE { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmployeeJob EmployeeJob { get; set; }
    }
}
