//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeCompPromotion
    {
        public int EmployeeCompPromotionNum { get; set; }
        public int EmpJobNum { get; set; }
        public string PromotionRange { get; set; }
        public Nullable<decimal> PromotionPct { get; set; }
        public Nullable<decimal> PromotionAmt { get; set; }
        public Nullable<decimal> HrlyPromotionAmt { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<int> NewJobNum { get; set; }
        public Nullable<int> PromotionPH { get; set; }
        public bool Eligibility { get; set; }
        public Nullable<bool> PromotionRequest { get; set; }
        public string NewGrade { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmployeeJob EmployeeJob { get; set; }
    }
}
