//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetailsCorrection
    {
        public int EmployeeDataCorrectionNum { get; set; }
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string PreferredName { get; set; }
        public string Gender { get; set; }
        public string JobCode { get; set; }
        public string JobTitle { get; set; }
        public string CurrentGrade { get; set; }
        public string BusinessUnit { get; set; }
        public string Function { get; set; }
        public string Department { get; set; }
        public string EmployeeClass { get; set; }
        public string PayrollStatus { get; set; }
        public string FLSAStatus { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<decimal> FTE { get; set; }
        public Nullable<int> ActualWorkHours { get; set; }
        public Nullable<int> TotalWorkHours { get; set; }
        public string WorkCountry { get; set; }
        public string WorkLocation { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string SupervisorID { get; set; }
        public string EmailAddress { get; set; }
        public string PayCurrency { get; set; }
        public Nullable<System.DateTime> LastPayChangeDate { get; set; }
        public string LastPayChangeReason { get; set; }
        public Nullable<decimal> CurrentHourlyRate { get; set; }
        public Nullable<decimal> CurrentAnnualizedSalary { get; set; }
        public Nullable<decimal> CurrentAnnualSalary { get; set; }
        public string PayrollSource { get; set; }
        public Nullable<decimal> SalaryMin { get; set; }
        public Nullable<decimal> SalaryMid { get; set; }
        public Nullable<decimal> SalaryMax { get; set; }
        public Nullable<System.DateTime> MeritProrationDate { get; set; }
        public Nullable<decimal> MeritProrationFactor { get; set; }
        public string MeritPerformanceRating { get; set; }
        public string MeritEligible { get; set; }
        public Nullable<decimal> MeritPct { get; set; }
        public Nullable<decimal> MeritAmount { get; set; }
        public string MeritIncreaseGuideline { get; set; }
        public Nullable<System.DateTime> MeritEffectiveDate { get; set; }
        public Nullable<decimal> LumpSumPct { get; set; }
        public Nullable<decimal> LumpSumAmount { get; set; }
        public Nullable<System.DateTime> LumpsumEffectiveDate { get; set; }
        public string PromotionEligible { get; set; }
        public Nullable<decimal> PromotionPct { get; set; }
        public Nullable<decimal> PromotionAmount { get; set; }
        public string PromoteTo { get; set; }
        public Nullable<System.DateTime> LastPromotionDate { get; set; }
        public Nullable<System.DateTime> PromotionEffectiveDate { get; set; }
        public string AdjustmentEligible { get; set; }
        public Nullable<decimal> AdjustmentPct { get; set; }
        public Nullable<decimal> AdjustmentAmount { get; set; }
        public Nullable<System.DateTime> AdjustmentEffectiveDate { get; set; }
        public Nullable<decimal> NewSalary { get; set; }
        public Nullable<decimal> NewHourlyRate { get; set; }
        public Nullable<decimal> Comparatio { get; set; }
        public Nullable<decimal> NewComparatio { get; set; }
        public string MoreInfo1 { get; set; }
        public string MoreInfo2 { get; set; }
        public string MoreInfo3 { get; set; }
        public string MoreInfo4 { get; set; }
        public string MoreInfo5 { get; set; }
        public string MoreInfo6 { get; set; }
        public string MoreInfo7 { get; set; }
        public string MoreInfo8 { get; set; }
        public string MoreInfo9 { get; set; }
        public string MoreInfo10 { get; set; }
        public string MoreInfo11 { get; set; }
        public string MoreInfo12 { get; set; }
        public string MoreInfo13 { get; set; }
        public string MoreInfo14 { get; set; }
        public string MoreInfo15 { get; set; }
        public string MoreInfo16 { get; set; }
        public string MoreInfo17 { get; set; }
        public string MoreInfo18 { get; set; }
        public string MoreInfo19 { get; set; }
        public string MoreInfo20 { get; set; }
        public string MoreInfo21 { get; set; }
        public string MoreInfo22 { get; set; }
        public string MoreInfo23 { get; set; }
        public Nullable<int> UserNum { get; set; }
    }
}
