//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public Grade()
        {
            this.EmployeeJobs = new HashSet<EmployeeJob>();
        }
    
        public int GradeNum { get; set; }
        public string GradeCode { get; set; }
        public string GradeDescr { get; set; }
        public Nullable<int> GradeOrder { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<EmployeeJob> EmployeeJobs { get; set; }
    }
}
