//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class InitiativesLink
    {
        public int InitiativesLinkNum { get; set; }
        public string LinkName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
        public string URL { get; set; }
        public bool IsManagerView { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public Nullable<int> AppMenuID { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
