//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketPayRange
    {
        public int MarketPayRangeNum { get; set; }
        public Nullable<int> JobNum { get; set; }
        public Nullable<int> GradeNum { get; set; }
        public Nullable<int> EmployeeNum { get; set; }
        public Nullable<decimal> CurrentMin { get; set; }
        public Nullable<decimal> CurrentMid { get; set; }
        public Nullable<decimal> CurrentMax { get; set; }
        public Nullable<decimal> FutureMin { get; set; }
        public Nullable<decimal> FutureMid { get; set; }
        public Nullable<decimal> FutureMax { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<decimal> HourlyCurrentMin { get; set; }
        public Nullable<decimal> HourlyCurrentMid { get; set; }
        public Nullable<decimal> HourlyCurrentMax { get; set; }
        public Nullable<decimal> HourlyFutureMin { get; set; }
        public Nullable<decimal> HourlyFutureMid { get; set; }
        public Nullable<decimal> HourlyFutureMax { get; set; }
    }
}
