//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaXmlTemplate
    {
        public int MetaXmlTemplateNum { get; set; }
        public string TemplateName { get; set; }
        public string TemplateSchemaName { get; set; }
        public string TemplateTableName { get; set; }
        public string TemplateFileName { get; set; }
        public string TemplateSchemaPath { get; set; }
        public string TemplateXMLpath { get; set; }
        public string TemplateDownloadpath { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> ExecutionOrder { get; set; }
        public string TableName { get; set; }
    }
}
