//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetaColumn
    {
        public int MetaColumnID { get; set; }
        public string FieldName { get; set; }
        public string ActualColumnName { get; set; }
        public string GeneralAliasName { get; set; }
        public string TemplateAliasName { get; set; }
        public bool MasterDisplay { get; set; }
        public bool PopupDisplay { get; set; }
        public bool GridDisplay { get; set; }
        public bool FilterDisplay { get; set; }
        public bool ExportDisplay { get; set; }
        public bool TemplateDisplay { get; set; }
        public bool IsMandate { get; set; }
        public bool IsTemplate { get; set; }
        public bool PopupDisplayDefaultValue { get; set; }
        public bool GridDisplayDefaultValue { get; set; }
        public bool FilterDisplayDefaultValue { get; set; }
        public bool ExportDisplayDefaultValue { get; set; }
        public bool TemplateDisplayDefaultValue { get; set; }
        public Nullable<bool> IsMandateDefaultValue { get; set; }
        public Nullable<bool> IsTemplateDefaultValue { get; set; }
        public string FunctionalGroup { get; set; }
        public string TableName { get; set; }
        public string TableKeyColumnName { get; set; }
        public string SampleData { get; set; }
        public string DataLength { get; set; }
        public string DataFormat { get; set; }
        public string FieldDescription { get; set; }
        public string RowOrder { get; set; }
        public string TemplateRowOrder { get; set; }
        public string ControlType { get; set; }
        public string PlaceHolder { get; set; }
        public string ControlFormat { get; set; }
        public string FieldInformation { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string RuleConfigurationKeyGroup { get; set; }
    }
}
