//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        public Module()
        {
            this.EmployeeCompApprovalLevels = new HashSet<EmployeeCompApprovalLevel>();
            this.EmployeeCompApprovalLevels1 = new HashSet<EmployeeCompApprovalLevel>();
            this.ProxyGroups = new HashSet<ProxyGroup>();
            this.ProxyManagers = new HashSet<ProxyManager>();
        }
    
        public int ModuleNum { get; set; }
        public string ModuleName { get; set; }
        public string ModuleKey { get; set; }
        public bool IsWorkflow { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<EmployeeCompApprovalLevel> EmployeeCompApprovalLevels { get; set; }
        public virtual ICollection<EmployeeCompApprovalLevel> EmployeeCompApprovalLevels1 { get; set; }
        public virtual ICollection<ProxyGroup> ProxyGroups { get; set; }
        public virtual ICollection<ProxyManager> ProxyManagers { get; set; }
    }
}
