//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgGroup
    {
        public OrgGroup()
        {
            this.EmployeeGroups = new HashSet<EmployeeGroup>();
            this.EmployeeGroupInclusionExclusions = new HashSet<EmployeeGroupInclusionExclusion>();
            this.OrgGroupAssignedCriterias = new HashSet<OrgGroupAssignedCriteria>();
            this.OrgGroupDetails = new HashSet<OrgGroupDetail>();
            this.OrgGroupTypes = new HashSet<OrgGroupType>();
            this.ProxyGroups = new HashSet<ProxyGroup>();
            this.ProxyPopulationAccesses = new HashSet<ProxyPopulationAccess>();
        }
    
        public int OrgGroupID { get; set; }
        public string GroupName { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<EmployeeGroup> EmployeeGroups { get; set; }
        public virtual ICollection<EmployeeGroupInclusionExclusion> EmployeeGroupInclusionExclusions { get; set; }
        public virtual ICollection<OrgGroupAssignedCriteria> OrgGroupAssignedCriterias { get; set; }
        public virtual ICollection<OrgGroupDetail> OrgGroupDetails { get; set; }
        public virtual ICollection<OrgGroupType> OrgGroupTypes { get; set; }
        public virtual ICollection<ProxyGroup> ProxyGroups { get; set; }
        public virtual ICollection<ProxyPopulationAccess> ProxyPopulationAccesses { get; set; }
    }
}
