//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgGroupType
    {
        public int OrgGroupTypeID { get; set; }
        public Nullable<int> OrgGroupID { get; set; }
        public Nullable<int> GroupTypeNum { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual GroupType GroupType { get; set; }
        public virtual OrgGroup OrgGroup { get; set; }
    }
}
