//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class PivotedEmployeeCompApprovalLevel
    {
        public int KeyNum { get; set; }
        public int EmpJobNum { get; set; }
        public int ApprovalManager { get; set; }
        public int ApprovalLevel { get; set; }
        public Nullable<int> ModuleNum { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
