//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProxyGroup
    {
        public int ProxyGroupID { get; set; }
        public int OrgGroupID { get; set; }
        public int UserID { get; set; }
        public bool IsReadOnly { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public int ModuleNum { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual AppUser AppUser { get; set; }
        public virtual OrgGroup OrgGroup { get; set; }
    }
}
