//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoundingType
    {
        public int RoundingTypeId { get; set; }
        public string RoundTypeKey { get; set; }
        public string RoundTypeValue { get; set; }
        public bool Active { get; set; }
    }
}
