//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubStatu
    {
        public SubStatu()
        {
            this.EmployeeJobs = new HashSet<EmployeeJob>();
        }
    
        public int SubStatusNum { get; set; }
        public string SubStatusCode { get; set; }
        public string SubStatusDescr { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ICollection<EmployeeJob> EmployeeJobs { get; set; }
    }
}
