//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class TriggerEmail
    {
        public int TriggerEmailNum { get; set; }
        public Nullable<int> ApprovalManagerEmpJobNum { get; set; }
        public string ApprovalManagerName { get; set; }
        public Nullable<int> RequesterEmpJobNum { get; set; }
        public string RequesterName { get; set; }
        public string EmailKey { get; set; }
        public string FromEmail { get; set; }
        public string ToEmail { get; set; }
        public string EmailCC { get; set; }
        public string EmailBCC { get; set; }
        public string Comment { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<int> DirectManagerNum { get; set; }
        public string DirectManagerName { get; set; }
        public Nullable<System.DateTime> InsertTime { get; set; }
        public Nullable<int> EmailStatus { get; set; }
    }
}
