//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public int UserMenuID { get; set; }
        public Nullable<int> AppMenuID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
    }
}
