//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAppUrlTracker
    {
        public int UserAppUrlTrackerID { get; set; }
        public string ClientUserID { get; set; }
        public string SecretKey { get; set; }
        public string RequestTimeStamp { get; set; }
        public string EncryptedMagicKey { get; set; }
        public string SiteUrl { get; set; }
        public Nullable<bool> IsEncrypted { get; set; }
    }
}
