//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.EntityManager.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class XmlProcess
    {
        public int XmlProcessNum { get; set; }
        public Nullable<int> UserNum { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string XmlFilename { get; set; }
        public string SheetName { get; set; }
        public string FileSourcePath { get; set; }
        public Nullable<int> ValidateStatus { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
        public Nullable<int> RecordCount { get; set; }
        public int MetaXmlTemplateNum { get; set; }
    }
}
