//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyLocation
    {
        public short CompanyLocationPK { get; set; }
        public Nullable<short> CompanyFK { get; set; }
        public string Location_Name { get; set; }
        public string Usage { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string City { get; set; }
        public string Statecode { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
        public string Reg_No { get; set; }
        public Nullable<byte> OccupancyType { get; set; }
        public Nullable<System.DateTime> Started_Date { get; set; }
        public bool IsActive { get; set; }
    }
}
