//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public decimal CustomerPK { get; set; }
        public Nullable<short> CompanyFK { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<byte> BusnType { get; set; }
        public string Tax_No { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string City { get; set; }
        public string Statecode { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
        public Nullable<decimal> MobileNo { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> IDType { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<short> CreatedLocationfk { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
