//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public decimal EmployeePK { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> EmployedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<decimal> PhoneNo { get; set; }
        public string Addressline1 { get; set; }
        public string Addressline2 { get; set; }
        public string City { get; set; }
        public string Statecode { get; set; }
        public string country { get; set; }
        public string pincode { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<byte> IDType { get; set; }
        public string ReferenceID { get; set; }
        public Nullable<short> DeptType { get; set; }
        public Nullable<short> Designation { get; set; }
        public Nullable<short> Location { get; set; }
        public Nullable<decimal> ManagerEmpFK { get; set; }
        public string ContactName { get; set; }
        public Nullable<decimal> ContactPhoneNo { get; set; }
        public Nullable<bool> ISAppUser { get; set; }
        public Nullable<decimal> AppuserFK { get; set; }
        public string EmployeeName { get; set; }
    }
}
