//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMaster
    {
        public short GroupMasterPK { get; set; }
        public Nullable<short> CompanyFK { get; set; }
        public string GroupName { get; set; }
        public Nullable<short> TopGroupFK { get; set; }
        public Nullable<byte> StatementType { get; set; }
        public Nullable<byte> Statementpart { get; set; }
        public Nullable<short> Groupprefix { get; set; }
        public Nullable<short> Displaysequence { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Updatedby { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
