//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TenantDatabase
    {
        public decimal TenantDatabasePK { get; set; }
        public Nullable<int> TenantFK { get; set; }
        public string DataBaseName { get; set; }
    }
}
