//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public byte UserRolePK { get; set; }
        public string UserRole1 { get; set; }
        public bool IsActive { get; set; }
    }
}
