//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppUser
    {
        public decimal AppUserPK { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public byte[] Passkey { get; set; }
        public Nullable<decimal> Logged { get; set; }
        public Nullable<byte> UserRole { get; set; }
        public Nullable<byte> LoginAttempt { get; set; }
        public Nullable<System.DateTime> Lastlogin { get; set; }
        public Nullable<System.DateTime> Lastlogout { get; set; }
        public Nullable<byte> UserStatus { get; set; }
    }
}
