//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvoiceDataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonCode
    {
        public decimal CommonCodePK { get; set; }
        public string CodeType { get; set; }
        public Nullable<byte> CodeID { get; set; }
        public string Code { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
