//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.Resource.HR.CommentResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CommentResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommentResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laserbeam.Resource.HR.CommentResources.CommentResource", typeof(CommentResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please explain why you are making this change..
        /// </summary>
        public static string BonusCommentTitle {
            get {
                return ResourceManager.GetString("BonusCommentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over established guidelines - please enter a justification.
        /// </summary>
        public static string BonusMandateComment {
            get {
                return ResourceManager.GetString("BonusMandateComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string CommentLinkText {
            get {
                return ResourceManager.GetString("CommentLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        public static string CommentPopupTitle {
            get {
                return ResourceManager.GetString("CommentPopupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment is required.
        /// </summary>
        public static string CommentSaveTitle {
            get {
                return ResourceManager.GetString("CommentSaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating of Development Opportunity requires a comment..
        /// </summary>
        public static string CompetencyRatingMandateText {
            get {
                return ResourceManager.GetString("CompetencyRatingMandateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We appreciate your feedback; please let us know how we can improve the user experience.
        /// </summary>
        public static string FeedBackComment {
            get {
                return ResourceManager.GetString("FeedBackComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide justification for exceeding guidelines.
        /// </summary>
        public static string MeritManditComment {
            get {
                return ResourceManager.GetString("MeritManditComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your comments in the box below as your manager will receive an email notification that changes have been made to your objectives..
        /// </summary>
        public static string NotifyEmployeeComment {
            get {
                return ResourceManager.GetString("NotifyEmployeeComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide your comments in the box below as your employee will receive an email notification that changes have been made to their objectives..
        /// </summary>
        public static string NotifyManagerComment {
            get {
                return ResourceManager.GetString("NotifyManagerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating of Does Not Meet Expectations or Below Expectations requires a comment..
        /// </summary>
        public static string ObjectiveRatingMandateText {
            get {
                return ResourceManager.GetString("ObjectiveRatingMandateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating of Does Not Meet Expectations or Below Expectations requires a comment..
        /// </summary>
        public static string OverallReviewMandateText {
            get {
                return ResourceManager.GetString("OverallReviewMandateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the reason(s) for reopening your employee&apos;s objectives. Your comments will be delivered to the employee via an email notification..
        /// </summary>
        public static string ReopenComment {
            get {
                return ResourceManager.GetString("ReopenComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Send.
        /// </summary>
        public static string SaveandSendButton {
            get {
                return ResourceManager.GetString("SaveandSendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to submit your objectives for manager acknowledgement. If you have any comments please use the box below as your manager will receive a notification to acknowledge your objectives..
        /// </summary>
        public static string SubmitComment {
            get {
                return ResourceManager.GetString("SubmitComment", resourceCulture);
            }
        }
    }
}
