//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIApplication.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TenantEntities : DbContext
    {
        public TenantEntities()
            : base("name=TenantEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tenant> Tenants { get; set; }
    
        public virtual ObjectResult<USP_PUT_NewDataBase_Result> USP_PUT_NewDataBase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_PUT_NewDataBase_Result>("USP_PUT_NewDataBase");
        }
    }
}
