//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laserbeam.Resource.HR.DashboardResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashboardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashboardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Laserbeam.Resource.HR.DashboardResources.DashboardResource", typeof(DashboardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight should add upto 100%.
        /// </summary>
        public static string AddWeight {
            get {
                return ResourceManager.GetString("AddWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal category is required to send request.
        /// </summary>
        public static string alert {
            get {
                return ResourceManager.GetString("alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVAL STATUS.
        /// </summary>
        public static string ApprovalStatus {
            get {
                return ResourceManager.GetString("ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPROVE.
        /// </summary>
        public static string APPROVE {
            get {
                return ResourceManager.GetString("APPROVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved successfully.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATEGORY.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETION %.
        /// </summary>
        public static string Completion {
            get {
                return ResourceManager.GetString("Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLETION DATE.
        /// </summary>
        public static string CompletionDate {
            get {
                return ResourceManager.GetString("CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Date.
        /// </summary>
        public static string CompletionEndDate {
            get {
                return ResourceManager.GetString("CompletionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department .
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s Objectives for Approval.
        /// </summary>
        public static string EEObj {
            get {
                return ResourceManager.GetString("EEObj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmpListPopup.
        /// </summary>
        public static string EmpListPopup {
            get {
                return ResourceManager.GetString("EmpListPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Name.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Events and Communications.
        /// </summary>
        public static string EventTitle {
            get {
                return ResourceManager.GetString("EventTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted and unweighted goal can not be submitted together.
        /// </summary>
        public static string GoalSubmitAlert {
            get {
                return ResourceManager.GetString("GoalSubmitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hire Date .
        /// </summary>
        public static string HireDate {
            get {
                return ResourceManager.GetString("HireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initiatives.
        /// </summary>
        public static string InitiativesTitle {
            get {
                return ResourceManager.GetString("InitiativesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title .
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2016 Laserbeam Software. All rights reserved..
        /// </summary>
        public static string LbsRights {
            get {
                return ResourceManager.GetString("LbsRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to www.laserbeamsoftware.com.
        /// </summary>
        public static string LbsWebsite {
            get {
                return ResourceManager.GetString("LbsWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L62.
        /// </summary>
        public static string MyObjectivesMenuID {
            get {
                return ResourceManager.GetString("MyObjectivesMenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 My Objectives.
        /// </summary>
        public static string MyObjectivesTitle {
            get {
                return ResourceManager.GetString("MyObjectivesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L70.
        /// </summary>
        public static string MyReviewMenuID {
            get {
                return ResourceManager.GetString("MyReviewMenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 My Review.
        /// </summary>
        public static string MyRevwTitle {
            get {
                return ResourceManager.GetString("MyRevwTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weights cannot be null.
        /// </summary>
        public static string NullWeightAlert {
            get {
                return ResourceManager.GetString("NullWeightAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No numbers above 100.
        /// </summary>
        public static string NumAlert {
            get {
                return ResourceManager.GetString("NumAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;s Objectives for Approval.
        /// </summary>
        public static string ObjApproval {
            get {
                return ResourceManager.GetString("ObjApproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBJECTIVES.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above progress bar indicates your objective setting status.
        /// </summary>
        public static string Progress_MyGoals_Text {
            get {
                return ResourceManager.GetString("Progress_MyGoals_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above progress bar indicates your review setting status.
        /// </summary>
        public static string Progress_MyReview_Text {
            get {
                return ResourceManager.GetString("Progress_MyReview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above progress bar indicates your direct reports objective setting status.
        /// </summary>
        public static string Progress_MyTeamGoals_Text {
            get {
                return ResourceManager.GetString("Progress_MyTeamGoals_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The above progress bar indicates your direct reports review setting status.
        /// </summary>
        public static string Progress_MyTeamReview_Text {
            get {
                return ResourceManager.GetString("Progress_MyTeamReview_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees with approved objectives.
        /// </summary>
        public static string Progress_TeamObjective_Approved {
            get {
                return ResourceManager.GetString("Progress_TeamObjective_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees with reopened objectives.
        /// </summary>
        public static string Progress_TeamObjective_Reopen {
            get {
                return ResourceManager.GetString("Progress_TeamObjective_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees with submitted objectives.
        /// </summary>
        public static string Progress_TeamObjective_Submitted {
            get {
                return ResourceManager.GetString("Progress_TeamObjective_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total employee count.
        /// </summary>
        public static string Progress_TeamObjective_Total {
            get {
                return ResourceManager.GetString("Progress_TeamObjective_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees yet to start objectives.
        /// </summary>
        public static string Progress_TeamObjective_YetToStart {
            get {
                return ResourceManager.GetString("Progress_TeamObjective_YetToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees with locked review.
        /// </summary>
        public static string Progress_TeamReview_Completed {
            get {
                return ResourceManager.GetString("Progress_TeamReview_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees review in progress.
        /// </summary>
        public static string Progress_TeamReview_InProgress {
            get {
                return ResourceManager.GetString("Progress_TeamReview_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees with reopened self review.
        /// </summary>
        public static string Progress_TeamReview_Reopen {
            get {
                return ResourceManager.GetString("Progress_TeamReview_Reopen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total employee count.
        /// </summary>
        public static string Progress_TeamReview_Total {
            get {
                return ResourceManager.GetString("Progress_TeamReview_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees review yet to start.
        /// </summary>
        public static string Progress_TeamReview_YetToStart {
            get {
                return ResourceManager.GetString("Progress_TeamReview_YetToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REOPEN.
        /// </summary>
        public static string REOPEN {
            get {
                return ResourceManager.GetString("REOPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reopened successfully.
        /// </summary>
        public static string Reopened {
            get {
                return ResourceManager.GetString("Reopened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Not Found.
        /// </summary>
        public static string ReportWarning {
            get {
                return ResourceManager.GetString("ReportWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string StatusBarTitle {
            get {
                return ResourceManager.GetString("StatusBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted successfully.
        /// </summary>
        public static string submitted {
            get {
                return ResourceManager.GetString("submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Name .
        /// </summary>
        public static string SupervisorName {
            get {
                return ResourceManager.GetString("SupervisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L63.
        /// </summary>
        public static string TeamObjectiveMenuID {
            get {
                return ResourceManager.GetString("TeamObjectiveMenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 Team Objectives.
        /// </summary>
        public static string TeamObjTitle {
            get {
                return ResourceManager.GetString("TeamObjTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L71.
        /// </summary>
        public static string TeamReviewMenuID {
            get {
                return ResourceManager.GetString("TeamReviewMenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015 Team Reviews.
        /// </summary>
        public static string TeamRevwTitle {
            get {
                return ResourceManager.GetString("TeamRevwTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOALS.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string TopObjectivesCategory {
            get {
                return ResourceManager.GetString("TopObjectivesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TopObjectivesTitle {
            get {
                return ResourceManager.GetString("TopObjectivesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight (%).
        /// </summary>
        public static string TopObjectivesWeight {
            get {
                return ResourceManager.GetString("TopObjectivesWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight:.
        /// </summary>
        public static string TotalWeight {
            get {
                return ResourceManager.GetString("TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEIGHT %.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total objective weight should not exceed 100.
        /// </summary>
        public static string WeightAlert {
            get {
                return ResourceManager.GetString("WeightAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total objective weight should meet 100%.
        /// </summary>
        public static string WeightAlert2 {
            get {
                return ResourceManager.GetString("WeightAlert2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All weighted goals should be submitted together.
        /// </summary>
        public static string WeightedGoals {
            get {
                return ResourceManager.GetString("WeightedGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All weighted goals should be submitted together.
        /// </summary>
        public static string WeightedGoalSubmitAlert {
            get {
                return ResourceManager.GetString("WeightedGoalSubmitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total objective weight should meet 100%.
        /// </summary>
        public static string WeightTotal {
            get {
                return ResourceManager.GetString("WeightTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Service .
        /// </summary>
        public static string YearsOfService {
            get {
                return ResourceManager.GetString("YearsOfService", resourceCulture);
            }
        }
    }
}
